spring:
  #  config mysql database
  datasource:
    url: "jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "${MYSQL_USERNAME}"
    password: "${MYSQL_PASSWORD}"
    initialization-mode: "always"
  #config JPA
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "update"
  #config jackson
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: "false"
    time-zone: "UTC"
  security:
    permitEndpoint:
      - api/auth/**
    corsAllowedOrigins:
      - https://example.com
    corsAllowedMethods:
      - POST
      - GET
    app:
      jwtSecret: "${JWT_SECRET}"
      jwtExpirationInMs: "300000"

logging:
  level:
    org:
      hibernate:
        SQL: "DEBUG"